In [1]:
import numpy as np


In [2]:
##Checkerboard Pattern (8x8) using 0s and 1s
checkerboard = np.indices((8, 8)).sum(axis=0) % 2
print("Checkerboard Pattern:\n", checkerboard)

Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [3]:
#Function to Flatten & Sort in Descending Order
def flatten_and_sort_desc(arr):
    return np.sort(arr.ravel())[::-1]

# Example usage:
arr = np.array([[3, 1], [4, 2]])
print("Flattened and Sorted Descending:\n", flatten_and_sort_desc(arr))

Flattened and Sorted Descending:
 [4 3 2 1]


In [4]:
# Subtract Row Mean from Each Row (Broadcasting)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
row_means = matrix.mean(axis=1, keepdims=True)
centered_matrix = matrix - row_means
print("Matrix with Row Means Subtracted:\n", centered_matrix)

Matrix with Row Means Subtracted:
 [[-1.  0.  1.]
 [-1.  0.  1.]]


In [5]:
# Find Elements Greater Than the Average
arr = np.array([1, 3, 5, 7, 9])
avg = arr.mean()
greater_than_avg = arr[arr > avg]
print("Elements Greater Than Average:\n", greater_than_avg)

Elements Greater Than Average:
 [7 9]


In [15]:
#Create a 5x5 Identity Matrix
import numpy as np

identity_matrix = np.eye(5)
print("5x5 Identity Matrix:\n", identity_matrix)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
#2. Replace All Odd Numbers in an Array with -1
arr = np.array([1, 2, 3, 4, 5])
arr[arr % 2 == 1] = -1
print("Replaced Odd Numbers with -1:\n", arr)

Replaced Odd Numbers with -1:
 [-1  2 -1  4 -1]


In [9]:
#3. Create a 4x4 Matrix and Extract Its Diagonal
matrix_4x4 = np.arange(1, 17).reshape(4, 4)
diagonal = np.diag(matrix_4x4)
print("4x4 Matrix:\n", matrix_4x4)
print("Diagonal:\n", diagonal)


4x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Diagonal:
 [ 1  6 11 16]


In [10]:
#4. Stack Two Arrays Vertically and Horizontally
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

vertical_stack = np.vstack((a, b))
horizontal_stack = np.hstack((a, b))

print("Vertical Stack:\n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)

Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [11]:
#5. Find Mean, Median, and Standard Deviation of an Array
data = np.array([1, 2, 3, 4, 5])

mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951


In [12]:
#6. Find Indices of the Maximum and Minimum Elements
arr = np.array([10, 20, 5, 8, 100])

max_index = np.argmax(arr)
min_index = np.argmin(arr)

print("Index of Max Element:", max_index)
print("Index of Min Element:", min_index)

Index of Max Element: 4
Index of Min Element: 2


In [13]:
#7. Create 3x3 Matrix with Values 1 to 9 and Normalize It

matrix = np.arange(1, 10).reshape(3, 3)
normalized = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))

print("Original Matrix:\n", matrix)
print("Normalized Matrix:\n", normalized)

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Matrix:
 [[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


In [ ]:
#8. Shuffle Elements of an Array Randomly
arr = np.arange(10)
np.random.shuffle(arr)
print("Shuffled Array:\n", arr)

Shuffled Array:
 [3 6 7 4 9 2 0 5 8 1]
